<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CentroCostoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('centrocosto')->insert([
            ['cco_id'=>0,'cco_codigo'=>'000','cco_descripcion'=>'SIN CENTRO DE COSTO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>1,'cco_codigo'=>'001','cco_descripcion'=>'EFECTIVO (CAJA Y BANCOS)','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>2,'cco_codigo'=>'002','cco_descripcion'=>'CUENTAS Y DOCTOS POR COBRAR','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>3,'cco_codigo'=>'003','cco_descripcion'=>'(-) RESERVA PARA CUENTAS INCOBRABLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>4,'cco_codigo'=>'004','cco_descripcion'=>'OTRAS CUENTAS Y DOCUMENTOS POR COBRAR','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>5,'cco_codigo'=>'005','cco_descripcion'=>'INVENTARIO FINAL','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>6,'cco_codigo'=>'006','cco_descripcion'=>'CRÉDITOS LÍQUIDOS Y EXIGIBLES PENDIENTES DE REINTEGRO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>7,'cco_codigo'=>'007','cco_descripcion'=>'INMUEBLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>8,'cco_codigo'=>'008','cco_descripcion'=>'MOBILIARIO Y EQUIPO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>9,'cco_codigo'=>'009','cco_descripcion'=>'MAQUINARIA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>10,'cco_codigo'=>'010','cco_descripcion'=>'VEHÍCULOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>11,'cco_codigo'=>'011','cco_descripcion'=>'EQUIPO DE CÓMPUTO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>12,'cco_codigo'=>'012','cco_descripcion'=>'OTROS ACTIVOS DEPRECIABLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>13,'cco_codigo'=>'013','cco_descripcion'=>'ACTIVOS AMORTIZABLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>14,'cco_codigo'=>'014','cco_descripcion'=>'INVERSIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>15,'cco_codigo'=>'015','cco_descripcion'=>'(-) DEPRECIACIONES ACUMULADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>16,'cco_codigo'=>'016','cco_descripcion'=>'(-) AMORTIZACIONES ACUMULADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>17,'cco_codigo'=>'017','cco_descripcion'=>'OTROS ACTIVOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>18,'cco_codigo'=>'018','cco_descripcion'=>'CUENTAS Y DOCUMENTOS POR PAGAR','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>19,'cco_codigo'=>'019','cco_descripcion'=>'PRÉSTAMOS BANCARIOS O FINANCIEROS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>20,'cco_codigo'=>'020','cco_descripcion'=>'OTROS PASIVOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>21,'cco_codigo'=>'021','cco_descripcion'=>'RESERVA PARA INDEMNIZACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>22,'cco_codigo'=>'022','cco_descripcion'=>'RESERVA LEGAL ACUMULADA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>23,'cco_codigo'=>'023','cco_descripcion'=>'OTRAS RESERVAS ACUMULADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>24,'cco_codigo'=>'024','cco_descripcion'=>'UTILIDAD ACUMULADA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>25,'cco_codigo'=>'025','cco_descripcion'=>'(-) PÉRDIDA ACUMULADA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>26,'cco_codigo'=>'026','cco_descripcion'=>'UTILIDAD DEL PERÍODO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>27,'cco_codigo'=>'027','cco_descripcion'=>'(-) PÉRDIDA DEL PERÍODO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>28,'cco_codigo'=>'028','cco_descripcion'=>'SUPERÁVIT POR REVALUACIÓN ACUMULADO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>29,'cco_codigo'=>'029','cco_descripcion'=>'CAPITAL','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>30,'cco_codigo'=>'030','cco_descripcion'=>'RENTAS NO AFECTAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>31,'cco_codigo'=>'031','cco_descripcion'=>'RENTAS DE CAPITAL FACTURADAS CON RETENCIÓN DEFINITIVA DEL IMPUESTO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>32,'cco_codigo'=>'032','cco_descripcion'=>'RENTAS DE CAPITAL FACTURADAS CON PAGO DIRECTO DEL IMPUESTO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>33,'cco_codigo'=>'033','cco_descripcion'=>'OTRAS RENTAS DE CAPITAL SUJETAS A RETENCIÓN DEFINITIVA (EJ.: PREMIOS DE LOTERÍA, INTERESES, DIVIDENDOS, ETC.)','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>34,'cco_codigo'=>'034','cco_descripcion'=>'VENTAS REALIZADAS A EXPORTADORES QUE EMITIERON FACTURAS ESPECIALES SEGÚN ARTÍCULO 52 “A” LEY DEL IVA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>35,'cco_codigo'=>'035','cco_descripcion'=>'INGRESOS POR EMISIÓN DE ACCIONES EN ÁREAS COMUNES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>36,'cco_codigo'=>'036','cco_descripcion'=>'INGRESOS POR NEGOCIACIÓN DE BIENES Y/O DERECHOS QUE NO SEAN DEL GIRO HABITUAL','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>37,'cco_codigo'=>'037','cco_descripcion'=>'COSTO Y MEJORAS DE LOS BIENES Y/O DERECHOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>38,'cco_codigo'=>'038','cco_descripcion'=>'(-) DEPRECIACIONES ACUMULADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>39,'cco_codigo'=>'039','cco_descripcion'=>'(-) AMORTIZACIONES ACUMULADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>40,'cco_codigo'=>'040','cco_descripcion'=>'(-) OTROS GASTOS INCURRIDOS PARA EFECTUAR LA TRANSACCIÓN','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>41,'cco_codigo'=>'041','cco_descripcion'=>'REMANENTE DE PÉRDIDAS DE CAPITAL DEL PERÍODO ANTERIOR','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>42,'cco_codigo'=>'042','cco_descripcion'=>'IMPUESTO SOBRE GANANCIAS DE CAPITAL PAGADO EN ESTE PERÍODO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>43,'cco_codigo'=>'043','cco_descripcion'=>'PRODUCCIÓN, VENTA Y COMERCIALIZACIÓN DE BIENES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>44,'cco_codigo'=>'044','cco_descripcion'=>'EXPORTACIONES DE BIENES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>45,'cco_codigo'=>'045','cco_descripcion'=>'EXPORTACIONES DE SERVICIOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>46,'cco_codigo'=>'046','cco_descripcion'=>'PRESTACIÓN DE SERVICIOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>47,'cco_codigo'=>'047','cco_descripcion'=>'ARRENDAMIENTOS Y SUBARRENDAMIENTOS DE BIENES MUEBLES E INMUEBLES DEL GIRO HABITUAL','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>48,'cco_codigo'=>'048','cco_descripcion'=>'SERVICIOS DE TRANSPORTE DE CARGA Y DE PERSONAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>49,'cco_codigo'=>'049','cco_descripcion'=>'SERVICIOS DE COMUNICACIONES, INCLUYENDO TELECOMUNICACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>50,'cco_codigo'=>'050','cco_descripcion'=>'SERVICIOS DE ASESORAMIENTO JURÍDICO, TÉCNICO, FINANCIERO, ADMINISTRATIVO O DE OTRA ÍNDOLE','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>51,'cco_codigo'=>'051','cco_descripcion'=>'ESPECTÁCULOS PÚBLICOS Y DE ACTUACIÓN','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>52,'cco_codigo'=>'052','cco_descripcion'=>'CUALQUIER FORMA DE NEGOCIACIÓN DE PELÍCULAS CINEMATOGRÁFICAS, CINTAS DE VIDEO, ETC.','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>53,'cco_codigo'=>'053','cco_descripcion'=>'SUBSIDIOS PERCIBIDOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>54,'cco_codigo'=>'054','cco_descripcion'=>'DIETAS, COMISIONES, VIÁTICOS NO SUJETOS A LIQUIDACIÓN, GASTOS DE REPRESENTACIÓN','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>55,'cco_codigo'=>'055','cco_descripcion'=>'HONORARIOS PROFESIONALES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>56,'cco_codigo'=>'056','cco_descripcion'=>'RENTAS EXENTAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>57,'cco_codigo'=>'057','cco_descripcion'=>'DONACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>58,'cco_codigo'=>'058','cco_descripcion'=>'RESARCIMIENTO DE PÉRDIDAS PATRIMONIALES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>59,'cco_codigo'=>'059','cco_descripcion'=>'GANANCIAS CAMBIARIAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>60,'cco_codigo'=>'060','cco_descripcion'=>'CUENTAS INCOBRABLES RECUPERADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>61,'cco_codigo'=>'061','cco_descripcion'=>'OTROS INGRESOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>62,'cco_codigo'=>'062','cco_descripcion'=>'INVENTARIO INICIAL DE MATERIA PRIMA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>63,'cco_codigo'=>'063','cco_descripcion'=>'(+) COMPRAS NETAS DE MATERIA PRIMA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>64,'cco_codigo'=>'064','cco_descripcion'=>'(+) IMPORTACIONES DE MATERIA PRIMA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>65,'cco_codigo'=>'065','cco_descripcion'=>'(+) GASTOS SOBRE COMPRAS DE MATERIA PRIMA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>66,'cco_codigo'=>'066','cco_descripcion'=>'(-) REBAJAS Y DEVOLUCIONES DE MATERIA PRIMA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>67,'cco_codigo'=>'067','cco_descripcion'=>'(-) INVENTARIO FINAL DE MATERIA PRIMA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>68,'cco_codigo'=>'068','cco_descripcion'=>'(+) MANO DE OBRA DIRECTA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>69,'cco_codigo'=>'069','cco_descripcion'=>'(+) GASTOS INDIRECTOS DE FABRICACIÓN','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>70,'cco_codigo'=>'070','cco_descripcion'=>'(+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>71,'cco_codigo'=>'071','cco_descripcion'=>'(-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>72,'cco_codigo'=>'072','cco_descripcion'=>'(+) INVENTARIO INICIAL DE MERCADERÍA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>73,'cco_codigo'=>'073','cco_descripcion'=>'(+) COMPRAS DE MERCADERÍA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>74,'cco_codigo'=>'074','cco_descripcion'=>'(+) IMPORTACIONES DE MERCADERÍA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>75,'cco_codigo'=>'075','cco_descripcion'=>'(-) INVENTARIO FINAL DE MERCADERÍA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>76,'cco_codigo'=>'076','cco_descripcion'=>'GASTOS INCURRIDOS EN LA PRESTACIÓN DE SERVICIOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>77,'cco_codigo'=>'077','cco_descripcion'=>'COMBUSTIBLES Y LUBRICANTES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>78,'cco_codigo'=>'078','cco_descripcion'=>'GASTOS DE TRANSPORTE','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>79,'cco_codigo'=>'079','cco_descripcion'=>'SUELDOS, SALARIOS Y OTRAS REMUNERACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>80,'cco_codigo'=>'080','cco_descripcion'=>'SUELDOS PAGADOS A SOCIOS O CONSEJEROS, CÓNYUGES O PARIENTES DENTRO DE LOS GRADOS DE LEY','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>81,'cco_codigo'=>'081','cco_descripcion'=>'AGUINALDOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>82,'cco_codigo'=>'082','cco_descripcion'=>'BONIFICACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>83,'cco_codigo'=>'083','cco_descripcion'=>'DIETAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>84,'cco_codigo'=>'084','cco_descripcion'=>'CUOTAS PATRONALES PAGADAS IGSS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>85,'cco_codigo'=>'085','cco_descripcion'=>'CUOTAS PATRONALES PAGADAS IRTRA E INTECAP','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>86,'cco_codigo'=>'086','cco_descripcion'=>'ASIGNACIONES PATRONALES POR JUBILACIONES, PENSIONES Y PRIMAS POR PLANES DE PREVISIÓN SOCIAL','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>87,'cco_codigo'=>'087','cco_descripcion'=>'INDEMNIZACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>88,'cco_codigo'=>'088','cco_descripcion'=>'INVERSIÓN EN BENEFICIO DE TRABAJADORES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>89,'cco_codigo'=>'089','cco_descripcion'=>'TIERRAS LABORABLES ADJUDICADAS GRATUITAMENTE A LOS TRABAJADORES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>90,'cco_codigo'=>'090','cco_descripcion'=>'PRIMAS DE SEGURO DE VIDA, POR ACCIDENTE O ENFERMEDAD DEL EMPLEADO','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>91,'cco_codigo'=>'091','cco_descripcion'=>'PRIMAS DE SEGUROS CONTRA INCENDI U OTROS RIESGOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>92,'cco_codigo'=>'092','cco_descripcion'=>'REASEGUROS Y REAFIANZAMIENTOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>93,'cco_codigo'=>'093','cco_descripcion'=>'ARRENDAMIENTOS DE BIENES MUEBLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>94,'cco_codigo'=>'094','cco_descripcion'=>'ARRENDAMIENTOS DE BIENES INMUEBLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>95,'cco_codigo'=>'095','cco_descripcion'=>'MEJORAS EFECTUADAS POR ARRENDATARIOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>96,'cco_codigo'=>'096','cco_descripcion'=>'IMPUESTOS, TASAS Y CONTRIBUCIONES PAGADAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>97,'cco_codigo'=>'097','cco_descripcion'=>'INTERESES Y OTROS CARGOS FINANCIEROS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>98,'cco_codigo'=>'098','cco_descripcion'=>'PÉRDIDAS POR EXTRAVÍO, ROTURA, DAÑO, EVAPORACIÓN, DESCOMPOSICIÓN O DESTRUCCIÓN DE LOS BIENES, POR DELITOS….','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>99,'cco_codigo'=>'099','cco_descripcion'=>'GASTOS DE MANTENIMIENTO Y REPARACIÓN','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>100,'cco_codigo'=>'100','cco_descripcion'=>'DEPRECIACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>101,'cco_codigo'=>'101','cco_descripcion'=>'AMORTIZACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>102,'cco_codigo'=>'102','cco_descripcion'=>'CUENTAS INCOBRABLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>103,'cco_codigo'=>'103','cco_descripcion'=>'RESERVAS TÉCNICAS Y MATEMÁTICAS (EXCLUSIVO PARA ASEGURADORAS Y ENTIDADES FINANCIERAS)','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>104,'cco_codigo'=>'104','cco_descripcion'=>'DONACIONES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>105,'cco_codigo'=>'105','cco_descripcion'=>'HONORARIOS POR SERVICIOS PROFESIONALES PRESTADOS EN EL PAÍS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>106,'cco_codigo'=>'106','cco_descripcion'=>'HONORARIOS POR SERVICIOS PROFESIONALES PRESTADOS DESDE EL EXTERIOR','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>107,'cco_codigo'=>'107','cco_descripcion'=>'VIÁTICOS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>108,'cco_codigo'=>'108','cco_descripcion'=>'REGALÍAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>109,'cco_codigo'=>'109','cco_descripcion'=>'GASTOS DE PROMOCIÓN, PUBLICIDAD Y PROPAGANDA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>110,'cco_codigo'=>'110','cco_descripcion'=>'DONACIONES A FAVOR DEL ESTADO, UNIVERSIDADES ENTIDADES CULTURALES O CIENTÍFICAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>111,'cco_codigo'=>'111','cco_descripcion'=>'PÉRDIDAS CAMBIARIAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>112,'cco_codigo'=>'112','cco_descripcion'=>'GASTOS DE VENTA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>113,'cco_codigo'=>'113','cco_descripcion'=>'GASTOS GENERALES (DIFERENTES A LOS ESTABLECIDOS EN LAS CASILLAS ANTERIORES)','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>114,'cco_codigo'=>'114','cco_descripcion'=>'(-) RENTAS EXENTAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>115,'cco_codigo'=>'115','cco_descripcion'=>'(+) COSTOS Y GASTOS PARA LA GENERACIÓN DE LAS RENTAS EXENTAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>116,'cco_codigo'=>'116','cco_descripcion'=>'(+) COSTOS Y GASTOS PARA LA GENERACIÓN DE LAS RENTAS NO AFECTAS','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>117,'cco_codigo'=>'117','cco_descripcion'=>'(+) COSTOS Y GASTOS DE RENTAS SUJETAS A RETENCIÓN DEFINITIVA SEGÚN ARTÍCULO 52 “A” LEY DEL IVA','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>118,'cco_codigo'=>'118','cco_descripcion'=>'(+) COSTOS Y GASTOS DE RENTAS DE CAPITAL','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>119,'cco_codigo'=>'119','cco_descripcion'=>'(+) OTROS COSTOS Y GASTOS NO DEDUCIBLES','cco_regimen'=>2,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>120,'cco_codigo'=>'001','cco_descripcion'=>'EFECTIVO (CAJA Y BANCOS)','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>121,'cco_codigo'=>'002','cco_descripcion'=>'CUENTAS Y DOCTOS POR COBRAR','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>122,'cco_codigo'=>'003','cco_descripcion'=>'(-) RESERVA PARA CUENTAS INCOBRABLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>123,'cco_codigo'=>'004','cco_descripcion'=>'OTRAS CUENTAS Y DOCUMENTOS POR COBRAR','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>124,'cco_codigo'=>'005','cco_descripcion'=>'INVENTARIO FINAL','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>125,'cco_codigo'=>'006','cco_descripcion'=>'CRÉDITOS LÍQUIDOS Y EXIGIBLES PENDIENTES DE REINTEGRO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>126,'cco_codigo'=>'007','cco_descripcion'=>'INMUEBLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>127,'cco_codigo'=>'008','cco_descripcion'=>'MOBILIARIO Y EQUIPO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>128,'cco_codigo'=>'009','cco_descripcion'=>'MAQUINARIA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>129,'cco_codigo'=>'010','cco_descripcion'=>'VEHÍCULOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>130,'cco_codigo'=>'011','cco_descripcion'=>'EQUIPO DE CÓMPUTO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>131,'cco_codigo'=>'012','cco_descripcion'=>'OTROS ACTIVOS DEPRECIABLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>132,'cco_codigo'=>'013','cco_descripcion'=>'ACTIVOS AMORTIZABLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>133,'cco_codigo'=>'014','cco_descripcion'=>'INVERSIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>134,'cco_codigo'=>'015','cco_descripcion'=>'(-) DEPRECIACIONES ACUMULADAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>135,'cco_codigo'=>'016','cco_descripcion'=>'(-) AMORTIZACIONES ACUMULADAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>136,'cco_codigo'=>'017','cco_descripcion'=>'OTROS ACTIVOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>137,'cco_codigo'=>'018','cco_descripcion'=>'CUENTAS Y DOCUMENTOS POR PAGAR','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>138,'cco_codigo'=>'019','cco_descripcion'=>'PRÉSTAMOS BANCARIOS O FINANCIEROS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>139,'cco_codigo'=>'020','cco_descripcion'=>'OTROS PASIVOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>140,'cco_codigo'=>'021','cco_descripcion'=>'RESERVA PARA INDEMNIZACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>141,'cco_codigo'=>'022','cco_descripcion'=>'RESERVA LEGAL ACUMULADA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>142,'cco_codigo'=>'023','cco_descripcion'=>'OTRAS RESERVAS ACUMULADAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>143,'cco_codigo'=>'024','cco_descripcion'=>'UTILIDAD ACUMULADA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>144,'cco_codigo'=>'025','cco_descripcion'=>'(-) PÉRDIDA ACUMULADA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>145,'cco_codigo'=>'026','cco_descripcion'=>'UTILIDAD DEL PERÍODO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>146,'cco_codigo'=>'027','cco_descripcion'=>'(-) PÉRDIDA DEL PERÍODO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>147,'cco_codigo'=>'028','cco_descripcion'=>'SUPERÁVIT POR REVALUACIÓN ACUMULADO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>148,'cco_codigo'=>'029','cco_descripcion'=>'CAPITAL','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>149,'cco_codigo'=>'030','cco_descripcion'=>'RENTAS NO AFECTAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>150,'cco_codigo'=>'031','cco_descripcion'=>'RENTAS DE CAPITAL FACTURADAS CON RETENCIÓN DEFINITIVA DEL IMPUESTO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>151,'cco_codigo'=>'032','cco_descripcion'=>'RENTAS DE CAPITAL FACTURADAS CON PAGO DIRECTO DEL IMPUESTO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>152,'cco_codigo'=>'033','cco_descripcion'=>'OTRAS RENTAS DE CAPITAL SUJETAS A RETENCIÓN DEFINITIVA (EJ.: PREMIOS DE LOTERÍA, INTERESES, DIVIDENDOS, ETC.)','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>153,'cco_codigo'=>'034','cco_descripcion'=>'VENTAS REALIZADAS A EXPORTADORES QUE EMITIERON FACTURAS ESPECIALES SEGÚN ARTÍCULO 52 “A” LEY DEL IVA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>154,'cco_codigo'=>'035','cco_descripcion'=>'INGRESOS POR EMISIÓN DE ACCIONES EN ÁREAS COMUNES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>155,'cco_codigo'=>'036','cco_descripcion'=>'INGRESOS POR NEGOCIACIÓN DE BIENES Y/O DERECHOS QUE NO SEAN DEL GIRO HABITUAL','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>156,'cco_codigo'=>'037','cco_descripcion'=>'COSTO Y MEJORAS DE LOS BIENES Y/O DERECHOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>157,'cco_codigo'=>'038','cco_descripcion'=>'(-) DEPRECIACIONES ACUMULADAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>158,'cco_codigo'=>'039','cco_descripcion'=>'(-) AMORTIZACIONES ACUMULADAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>159,'cco_codigo'=>'040','cco_descripcion'=>'(-) OTROS GASTOS INCURRIDOS PARA EFECTUAR LA TRANSACCIÓN','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>160,'cco_codigo'=>'041','cco_descripcion'=>'REMANENTE DE PÉRDIDAS DE CAPITAL DEL PERÍODO ANTERIOR','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>161,'cco_codigo'=>'042','cco_descripcion'=>'IMPUESTO SOBRE GANANCIAS DE CAPITAL PAGADO EN ESTE PERÍODO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>162,'cco_codigo'=>'043','cco_descripcion'=>'TOTAL RENTAS DE ACTIVIDADES LUCRATIVAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>163,'cco_codigo'=>'044','cco_descripcion'=>'(-) RENTAS EXENTAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>164,'cco_codigo'=>'045','cco_descripcion'=>'IMPUESTO DETERMINADO SEGÚN DECLARACIONES MENSUALES DE ESTE PERÍODO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>165,'cco_codigo'=>'046','cco_descripcion'=>'(-) VALOR DE RETENCIONES QUE LE PRACTICARON EN ESTE PERÍODO SEGÚN DECLARACIONES MENSUALES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>166,'cco_codigo'=>'047','cco_descripcion'=>'(=) SALDO DEL IMPUESTO DETERMINADO EN ESTE PERÍODO SEGÚN DECLARACIONES MENSUALES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>167,'cco_codigo'=>'048','cco_descripcion'=>'(-) ISO ACREDITADO EN ESTE PERÍODO SEGÚN DECLARACIONES MENSUALES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>168,'cco_codigo'=>'049','cco_descripcion'=>'(-) INCENTIVOS FISCALES; DECRETO 29-89, 65-89, 52-2003 Y OTROS.','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>169,'cco_codigo'=>'050','cco_descripcion'=>'(-) IMPUESTO PAGADO DECLARACIONES MENSUALES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>170,'cco_codigo'=>'051','cco_descripcion'=>'(=) EXCEDENTE DE RETENCIONES EN ESTE PERÍODO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>171,'cco_codigo'=>'052','cco_descripcion'=>'COSTOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>172,'cco_codigo'=>'053','cco_descripcion'=>'GASTOS DE ADMINISTRACION','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>173,'cco_codigo'=>'054','cco_descripcion'=>'GASTOS FINANCIEROS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>174,'cco_codigo'=>'055','cco_descripcion'=>'PRODUCTOS FINANCIEROS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>175,'cco_codigo'=>'056','cco_descripcion'=>'GASTOS NO DEDUCIBLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>176,'cco_codigo'=>'057','cco_descripcion'=>'IMPUESTO SOBRE LA RENTA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>177,'cco_codigo'=>'076','cco_descripcion'=>'GASTOS INCURRIDOS EN LA PRESTACIÓN DE SERVICIOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>178,'cco_codigo'=>'077','cco_descripcion'=>'COMBUSTIBLES Y LUBRICANTES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>179,'cco_codigo'=>'078','cco_descripcion'=>'GASTOS DE TRANSPORTE','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>180,'cco_codigo'=>'079','cco_descripcion'=>'SUELDOS, SALARIOS Y OTRAS REMUNERACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>181,'cco_codigo'=>'080','cco_descripcion'=>'SUELDOS PAGADOS A SOCIOS O CONSEJEROS, CÓNYUGES O PARIENTES DENTRO DE LOS GRADOS DE LEY','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>182,'cco_codigo'=>'081','cco_descripcion'=>'AGUINALDOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>183,'cco_codigo'=>'082','cco_descripcion'=>'BONIFICACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>184,'cco_codigo'=>'083','cco_descripcion'=>'DIETAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>185,'cco_codigo'=>'084','cco_descripcion'=>'CUOTAS PATRONALES PAGADAS IGSS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>186,'cco_codigo'=>'085','cco_descripcion'=>'CUOTAS PATRONALES PAGADAS IRTRA E INTECAP','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>187,'cco_codigo'=>'086','cco_descripcion'=>'ASIGNACIONES PATRONALES POR JUBILACIONES, PENSIONES Y PRIMAS POR PLANES DE PREVISIÓN SOCIAL','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>188,'cco_codigo'=>'087','cco_descripcion'=>'INDEMNIZACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>189,'cco_codigo'=>'088','cco_descripcion'=>'INVERSIÓN EN BENEFICIO DE TRABAJADORES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>190,'cco_codigo'=>'089','cco_descripcion'=>'TIERRAS LABORABLES ADJUDICADAS GRATUITAMENTE A LOS TRABAJADORES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>191,'cco_codigo'=>'090','cco_descripcion'=>'PRIMAS DE SEGURO DE VIDA, POR ACCIDENTE O ENFERMEDAD DEL EMPLEADO','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>192,'cco_codigo'=>'091','cco_descripcion'=>'PRIMAS DE SEGUROS CONTRA INCENDI U OTROS RIESGOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>193,'cco_codigo'=>'092','cco_descripcion'=>'REASEGUROS Y REAFIANZAMIENTOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>194,'cco_codigo'=>'093','cco_descripcion'=>'ARRENDAMIENTOS DE BIENES MUEBLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>195,'cco_codigo'=>'094','cco_descripcion'=>'ARRENDAMIENTOS DE BIENES INMUEBLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>196,'cco_codigo'=>'095','cco_descripcion'=>'MEJORAS EFECTUADAS POR ARRENDATARIOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>197,'cco_codigo'=>'096','cco_descripcion'=>'IMPUESTOS, TASAS Y CONTRIBUCIONES PAGADAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>198,'cco_codigo'=>'097','cco_descripcion'=>'INTERESES Y OTROS CARGOS FINANCIEROS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>199,'cco_codigo'=>'098','cco_descripcion'=>'PÉRDIDAS POR EXTRAVÍO, ROTURA, DAÑO, EVAPORACIÓN, DESCOMPOSICIÓN O DESTRUCCIÓN DE LOS BIENES, POR DELITOS….','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>200,'cco_codigo'=>'099','cco_descripcion'=>'GASTOS DE MANTENIMIENTO Y REPARACIÓN','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>201,'cco_codigo'=>'100','cco_descripcion'=>'DEPRECIACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>202,'cco_codigo'=>'101','cco_descripcion'=>'AMORTIZACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>203,'cco_codigo'=>'102','cco_descripcion'=>'CUENTAS INCOBRABLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>204,'cco_codigo'=>'103','cco_descripcion'=>'RESERVAS TÉCNICAS Y MATEMÁTICAS (EXCLUSIVO PARA ASEGURADORAS Y ENTIDADES FINANCIERAS)','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>205,'cco_codigo'=>'104','cco_descripcion'=>'DONACIONES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>206,'cco_codigo'=>'105','cco_descripcion'=>'HONORARIOS POR SERVICIOS PROFESIONALES PRESTADOS EN EL PAÍS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>207,'cco_codigo'=>'106','cco_descripcion'=>'HONORARIOS POR SERVICIOS PROFESIONALES PRESTADOS DESDE EL EXTERIOR','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>208,'cco_codigo'=>'107','cco_descripcion'=>'VIÁTICOS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>209,'cco_codigo'=>'108','cco_descripcion'=>'REGALÍAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>210,'cco_codigo'=>'109','cco_descripcion'=>'GASTOS DE PROMOCIÓN, PUBLICIDAD Y PROPAGANDA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>211,'cco_codigo'=>'110','cco_descripcion'=>'DONACIONES A FAVOR DEL ESTADO, UNIVERSIDADES ENTIDADES CULTURALES O CIENTÍFICAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>212,'cco_codigo'=>'111','cco_descripcion'=>'PÉRDIDAS CAMBIARIAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>213,'cco_codigo'=>'112','cco_descripcion'=>'GASTOS DE VENTA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>214,'cco_codigo'=>'113','cco_descripcion'=>'GASTOS GENERALES (DIFERENTES A LOS ESTABLECIDOS EN LAS CASILLAS ANTERIORES)','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>215,'cco_codigo'=>'114','cco_descripcion'=>'(-) RENTAS EXENTAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>216,'cco_codigo'=>'115','cco_descripcion'=>'(+) COSTOS Y GASTOS PARA LA GENERACIÓN DE LAS RENTAS EXENTAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>217,'cco_codigo'=>'116','cco_descripcion'=>'(+) COSTOS Y GASTOS PARA LA GENERACIÓN DE LAS RENTAS NO AFECTAS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>218,'cco_codigo'=>'117','cco_descripcion'=>'(+) COSTOS Y GASTOS DE RENTAS SUJETAS A RETENCIÓN DEFINITIVA SEGÚN ARTÍCULO 52 “A” LEY DEL IVA','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>219,'cco_codigo'=>'118','cco_descripcion'=>'(+) COSTOS Y GASTOS DE RENTAS DE CAPITAL','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>220,'cco_codigo'=>'119','cco_descripcion'=>'(+) OTROS COSTOS Y GASTOS NO DEDUCIBLES','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
            ['cco_id'=>221,'cco_codigo'=>'120','cco_descripcion'=>'PRODUCTOS FINANCIEROS','cco_regimen'=>1,'created_at'=>Carbon::now()->format('Y-m-d H:i:s')],
        ]);
    }
}
