<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clientes')->insert([
            ['cli_persona'=>372,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>373,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>374,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>375,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>376,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>377,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>378,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>379,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>380,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>381,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>382,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>383,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>384,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>385,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>386,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>387,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>388,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>389,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>390,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>391,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>392,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>393,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>394,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>395,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>396,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>397,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>398,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>399,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>400,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>401,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>402,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>403,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>404,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>405,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>406,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>407,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>408,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>409,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>410,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>411,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>412,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>413,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>414,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>415,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>416,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>417,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>418,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>419,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>420,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>421,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>422,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>423,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>424,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>425,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>426,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>427,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>428,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>429,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>430,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>431,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>432,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>433,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>434,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>435,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>436,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>437,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>438,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>439,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>440,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>441,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>442,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>443,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>444,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>445,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>446,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>447,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>448,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>449,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>450,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>451,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>452,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>453,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>454,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>455,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>456,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>457,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>458,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>459,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>460,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>461,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>462,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>463,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>464,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>465,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>466,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>467,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>468,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>469,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>470,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>471,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>472,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>473,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>474,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>475,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>476,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>477,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>478,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>479,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>480,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>481,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>482,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>483,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>484,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>485,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>486,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>487,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>488,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>489,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>490,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>491,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>492,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>493,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>494,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>495,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>496,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>497,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>498,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>499,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>500,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>501,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>502,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>503,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>504,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>505,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>506,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>507,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>508,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>509,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>510,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>511,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>512,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>108,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>513,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>514,'cli_tipoCliente'=>1,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>515,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>516,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>517,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>134,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>518,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>519,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>520,'cli_tipoCliente'=>3,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>521,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>522,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>523,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>524,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>525,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>526,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>527,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>528,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>529,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>530,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>531,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>532,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>533,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>207,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>534,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>535,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>536,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>537,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>538,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>539,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>540,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>541,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>542,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>543,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>544,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>545,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>106,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>150,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>546,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>547,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>548,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>549,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>550,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>551,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>552,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
['cli_persona'=>553,'cli_tipoCliente'=>2,'cli_credito'=>0,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],




        ]);
    }
}
