<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepMunSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('depmun')->insert([
            ['dep_id' => '00000', 'dep_descripcion' => 'SIN MUNICIPIO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0000', 'dep_descripcion' => 'METROPOLITANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II0000', 'dep_descripcion' => 'NORTE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0000', 'dep_descripcion' => 'NORORIENTE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0000', 'dep_descripcion' => 'SURORIENTE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0000', 'dep_descripcion' => 'CENTRAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0000', 'dep_descripcion' => 'SUROCCIDENTE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII0000', 'dep_descripcion' => 'NOROCCIDENTE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VIII0000', 'dep_descripcion' => 'PETEN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0100', 'dep_descripcion' => 'GUATEMALA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0101', 'dep_descripcion' => 'GUATEMALA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0102', 'dep_descripcion' => 'SANTA CATARINA PINULA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0103', 'dep_descripcion' => 'SAN JOSÉ PINULA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0104', 'dep_descripcion' => 'SAN JOSÉ DEL GOLFO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0105', 'dep_descripcion' => 'PALENCIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0106', 'dep_descripcion' => 'CHINAUTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0107', 'dep_descripcion' => 'SAN PEDRO AYAMPUC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0108', 'dep_descripcion' => 'MIXCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0109', 'dep_descripcion' => 'SAN PEDRO SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0110', 'dep_descripcion' => 'SAN JUAN SACATÉPEQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0111', 'dep_descripcion' => 'SAN RAYMUNDO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0112', 'dep_descripcion' => 'CHUARRANCHO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0113', 'dep_descripcion' => 'FRAIJANES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0114', 'dep_descripcion' => 'AMATITLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0115', 'dep_descripcion' => 'VILLA NUEVA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0116', 'dep_descripcion' => 'VILLA CANALES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'I0117', 'dep_descripcion' => 'PETAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0200', 'dep_descripcion' => 'EL PROGRESO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0201', 'dep_descripcion' => 'GUASTATOYA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0202', 'dep_descripcion' => 'MORAZÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0203', 'dep_descripcion' => 'SAN AGUSTÍN ACASAGUASTLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0204', 'dep_descripcion' => 'SAN CRISTÓBAL ACASAGUASTLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0205', 'dep_descripcion' => 'EL JÍCARO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0206', 'dep_descripcion' => 'SANSARE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0207', 'dep_descripcion' => 'SANARATE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III0208', 'dep_descripcion' => 'SAN ANTONIO LA PAZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0300', 'dep_descripcion' => 'SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0301', 'dep_descripcion' => 'ANTIGUA GUATEMALA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0302', 'dep_descripcion' => 'JOCOTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0303', 'dep_descripcion' => 'PASTORES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0304', 'dep_descripcion' => 'SUMPANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0305', 'dep_descripcion' => 'STO. DOMINGO XENACOJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0306', 'dep_descripcion' => 'SANTIAGO SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0307', 'dep_descripcion' => 'SAN BARTOLOMÉ MILLPAS ALTAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0308', 'dep_descripcion' => 'SAN LUCAS SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0309', 'dep_descripcion' => 'SANTA LUCIA MILPAS ALTAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0310', 'dep_descripcion' => 'MAGDALENA MILPAS ALTAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0311', 'dep_descripcion' => 'SANTA MARÍA DE JESÚS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0312', 'dep_descripcion' => 'CIUDAD VIEJA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0313', 'dep_descripcion' => 'SAN MIGUEL DUEÑAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0314', 'dep_descripcion' => 'ALOTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0315', 'dep_descripcion' => 'SAN ANTONIO AGUAS CALIENTES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0316', 'dep_descripcion' => 'SANTA CATARINA BARAHONA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0400', 'dep_descripcion' => 'CHIMALTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0401', 'dep_descripcion' => 'CHIMALTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0402', 'dep_descripcion' => 'SAN JOSÉ POAQUIL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0403', 'dep_descripcion' => 'SAN MARTÍN JILOTEPEQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0404', 'dep_descripcion' => 'COMALAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0405', 'dep_descripcion' => 'SANTA APOLONIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0406', 'dep_descripcion' => 'TECPÁN GUATEMALA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0407', 'dep_descripcion' => 'PATZÚN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0408', 'dep_descripcion' => 'POCHUTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0409', 'dep_descripcion' => 'PATZICIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0410', 'dep_descripcion' => 'SANTA CRUZ BALANYÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0411', 'dep_descripcion' => 'ACATENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0412', 'dep_descripcion' => 'YEPOCAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0413', 'dep_descripcion' => 'SAN ANDRÉS IZTAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0414', 'dep_descripcion' => 'PARRAMOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0415', 'dep_descripcion' => 'ZARAGOZA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0416', 'dep_descripcion' => 'EL TEJAR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0500', 'dep_descripcion' => 'ESCUINTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0501', 'dep_descripcion' => 'ESCUINTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0502', 'dep_descripcion' => 'SANTA LUCÍA COTZUMALGUAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0503', 'dep_descripcion' => 'LA DEMOCRACIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0504', 'dep_descripcion' => 'SIQUINALÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0505', 'dep_descripcion' => 'MASAGUA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0506', 'dep_descripcion' => 'TIQUISATE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0507', 'dep_descripcion' => 'LA GOMERA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0508', 'dep_descripcion' => 'GUANAGAZAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0509', 'dep_descripcion' => 'SAN JOSÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0510', 'dep_descripcion' => 'IZTAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0511', 'dep_descripcion' => 'PALÍN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0512', 'dep_descripcion' => 'SAN VICENTE PACAYA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'V0513', 'dep_descripcion' => 'NUEVA CONCEPCIÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0600', 'dep_descripcion' => 'SANTA ROSA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0601', 'dep_descripcion' => 'CUILAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0602', 'dep_descripcion' => 'BARBERENA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0603', 'dep_descripcion' => 'SANTA ROSA DE LIMA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0604', 'dep_descripcion' => 'CASILLAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0605', 'dep_descripcion' => 'SAN RAFAEL LAS FLORES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0606', 'dep_descripcion' => 'ORATORIO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0607', 'dep_descripcion' => 'SAN JUAN TECUACO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0608', 'dep_descripcion' => 'CHIQUIMULILLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0609', 'dep_descripcion' => 'TAXISCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0610', 'dep_descripcion' => 'SANTA MARÍA IXHUATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0611', 'dep_descripcion' => 'GUAZACAPÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0612', 'dep_descripcion' => 'SANTA CRUZ NARANJO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0613', 'dep_descripcion' => 'PUEBLO NUEVO VIÑAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV0614', 'dep_descripcion' => 'NUEVA SANTA ROSA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0700', 'dep_descripcion' => 'SOLOLÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0701', 'dep_descripcion' => 'SOLOLÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0702', 'dep_descripcion' => 'SAN JOSÉ CHACAYÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0703', 'dep_descripcion' => 'SANTA MARÍA VISITACIÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0704', 'dep_descripcion' => 'SANTA LUCÍA UTATLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0705', 'dep_descripcion' => 'NAHUALÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0706', 'dep_descripcion' => 'SANTA CATARINA IXTAHUACÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0707', 'dep_descripcion' => 'SANTA CLARA LA LAGUNA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0708', 'dep_descripcion' => 'CONCEPCIÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0709', 'dep_descripcion' => 'SAN ANDRÉS SEMETABAJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0710', 'dep_descripcion' => 'PANAJACHEL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0711', 'dep_descripcion' => 'SANTA CATARINA PALOPÓ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0712', 'dep_descripcion' => 'SAN ANTONIO PALOPÓ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0713', 'dep_descripcion' => 'SAN LUCAS TOLIMÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0714', 'dep_descripcion' => 'SANTA CRUZ LA LAGUNA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0715', 'dep_descripcion' => 'SAN PABLO LA LAGUNA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0716', 'dep_descripcion' => 'SAN MARCOS LA LAGUNA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0717', 'dep_descripcion' => 'SAN JUAN LA LAGUNA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0718', 'dep_descripcion' => 'SAN PEDRO LA LAGUNA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0719', 'dep_descripcion' => 'SANTIAGO ATITLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0800', 'dep_descripcion' => 'TOTONICAPÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0801', 'dep_descripcion' => 'TOTONICAPÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0802', 'dep_descripcion' => 'SAN CRISTÓBAL TOTONICAPÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0803', 'dep_descripcion' => 'SAN FRANCISCO EL ALTO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0804', 'dep_descripcion' => 'SAN ANDRÉS XECUL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0805', 'dep_descripcion' => 'MOMOSTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0806', 'dep_descripcion' => 'SANTA MARÍA CHIQUIMULA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0807', 'dep_descripcion' => 'SANTA LUCÍA LA REFORMA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0808', 'dep_descripcion' => 'SAN BARTOLO AGUAS CALIENTES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0900', 'dep_descripcion' => 'QUETZALTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0901', 'dep_descripcion' => 'QUETZALTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0902', 'dep_descripcion' => 'SALCAJÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0903', 'dep_descripcion' => 'OLINTEPEQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0904', 'dep_descripcion' => 'SAN CARLOS SIJA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0905', 'dep_descripcion' => 'SIBILIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0906', 'dep_descripcion' => 'CABRICÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0907', 'dep_descripcion' => 'CAJOLÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0908', 'dep_descripcion' => 'SAN MIGUEL SIGUILÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0909', 'dep_descripcion' => 'SAN JUAN OSTUNCALCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0910', 'dep_descripcion' => 'SAN MATEO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0911', 'dep_descripcion' => 'CONCEPCIÓN CHIQUIRICHAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0912', 'dep_descripcion' => 'SAN MARTÍN SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0913', 'dep_descripcion' => 'ALMOLONGA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0914', 'dep_descripcion' => 'CANTEL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0915', 'dep_descripcion' => 'HUITÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0916', 'dep_descripcion' => 'ZUNIL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0917', 'dep_descripcion' => 'COLOMBA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0918', 'dep_descripcion' => 'SAN FRANCISCO LA UNIÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0919', 'dep_descripcion' => 'EL PALMAR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0920', 'dep_descripcion' => 'COATEPEQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0921', 'dep_descripcion' => 'GÉNOVA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0922', 'dep_descripcion' => 'FLORES COSTA CUCA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0923', 'dep_descripcion' => 'LA ESPERANZA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI0924', 'dep_descripcion' => 'PALESTINA DE LOS ALTOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1000', 'dep_descripcion' => 'SUCHITEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1001', 'dep_descripcion' => 'MAZATENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1002', 'dep_descripcion' => 'CUYOTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1003', 'dep_descripcion' => 'SAN FRANCISCO ZAPOTITLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1004', 'dep_descripcion' => 'SAN BERNARDINO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1005', 'dep_descripcion' => 'SAN JOSÉ EL ÍDOLO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1006', 'dep_descripcion' => 'SANTO DOMINGO SUCHITEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1007', 'dep_descripcion' => 'SAN LORENZO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1008', 'dep_descripcion' => 'SAMAYAC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1009', 'dep_descripcion' => 'SAN PABLO JOCOPILAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1010', 'dep_descripcion' => 'SAN ANTONIO SUCHITEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1011', 'dep_descripcion' => 'SAN MIGUEL PANÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1012', 'dep_descripcion' => 'SAN GABRIEL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1013', 'dep_descripcion' => 'CHICACAO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1014', 'dep_descripcion' => 'PATULUL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1015', 'dep_descripcion' => 'SANTA BÁRBARA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1016', 'dep_descripcion' => 'SAN JUAN BAUTISTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1017', 'dep_descripcion' => 'SANTO TOMÁS LA UNIÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1018', 'dep_descripcion' => 'ZUNILITO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1019', 'dep_descripcion' => 'PUEBLO NUEVO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1020', 'dep_descripcion' => 'RÍO BRAVO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1100', 'dep_descripcion' => 'RETALHULEU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1101', 'dep_descripcion' => 'RETALHULEU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1102', 'dep_descripcion' => 'SAN SEBASTIÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1103', 'dep_descripcion' => 'SANTA CRUZ MULUÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1104', 'dep_descripcion' => 'SAN MARTÍN ZAPOTITLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1105', 'dep_descripcion' => 'SAN FELIPE RETALHULEU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1106', 'dep_descripcion' => 'SAN ANDRÉS VILLA SECA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1107', 'dep_descripcion' => 'CHAMPERICO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1108', 'dep_descripcion' => 'NUEVO SAN CARLOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1109', 'dep_descripcion' => 'EL ASINTAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1200', 'dep_descripcion' => 'SAN MARCOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1201', 'dep_descripcion' => 'SAN MARCOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1202', 'dep_descripcion' => 'SAN PEDRO SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1203', 'dep_descripcion' => 'SAN ANTONIO SACATEPÉQUEZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1204', 'dep_descripcion' => 'COMITANCILLO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1205', 'dep_descripcion' => 'SAN MIGUEL IXTAHUACÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1206', 'dep_descripcion' => 'CONCEPCIÓN TUTUAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1207', 'dep_descripcion' => 'TACANÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1208', 'dep_descripcion' => 'SIBINAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1209', 'dep_descripcion' => 'TAJUMULCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1210', 'dep_descripcion' => 'TEJUTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1211', 'dep_descripcion' => 'SAN RAFAEL PIE DE LA CUESTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1212', 'dep_descripcion' => 'NUEVO PROGRESO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1213', 'dep_descripcion' => 'EL TUMBADOR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1214', 'dep_descripcion' => 'EL RODEO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1215', 'dep_descripcion' => 'MALACATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1216', 'dep_descripcion' => 'CATARINA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1217', 'dep_descripcion' => 'AYUTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1218', 'dep_descripcion' => 'OCÓS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1219', 'dep_descripcion' => 'SAN PABLO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1220', 'dep_descripcion' => 'EL QUETZAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1221', 'dep_descripcion' => 'LA REFORMA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1222', 'dep_descripcion' => 'PAJAPITA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1223', 'dep_descripcion' => 'IXCHIGUÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1224', 'dep_descripcion' => 'SAN JOSÉ OJETENAM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1225', 'dep_descripcion' => 'SAN CRISTÓBAL CUCHO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1226', 'dep_descripcion' => 'SIPACAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1227', 'dep_descripcion' => 'ESQUIPULAS PALO GORDO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1228', 'dep_descripcion' => 'RÍO BLANCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VI1229', 'dep_descripcion' => 'SAN LORENZO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1300', 'dep_descripcion' => 'HUEHUETENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1301', 'dep_descripcion' => 'HUEHUETENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1302', 'dep_descripcion' => 'CHIANTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1303', 'dep_descripcion' => 'MALACATANCITO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1304', 'dep_descripcion' => 'CUILCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1305', 'dep_descripcion' => 'NENTÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1306', 'dep_descripcion' => 'SAN PEDRO NECTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1307', 'dep_descripcion' => 'JACALTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1308', 'dep_descripcion' => 'SOLOMA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1309', 'dep_descripcion' => 'SAN IDELFONSO IXTAHUACÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1310', 'dep_descripcion' => 'SANTA BÁRBARA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1311', 'dep_descripcion' => 'LA LIBERTAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1312', 'dep_descripcion' => 'LA DEMOCRACIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1313', 'dep_descripcion' => 'SAN MIGUEL ACATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1314', 'dep_descripcion' => 'SAN RAFAEL LA INDEPENCIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1315', 'dep_descripcion' => 'TODOS SANTOS CUCHUMATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1316', 'dep_descripcion' => 'SAN JUAN ATITÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1317', 'dep_descripcion' => 'SANTA EULALIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1318', 'dep_descripcion' => 'SAN MATEO IXTATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1319', 'dep_descripcion' => 'COLOTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1320', 'dep_descripcion' => 'SAN SEBASTIÁN HUEHUETENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1321', 'dep_descripcion' => 'TECTITÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1322', 'dep_descripcion' => 'CONCEPCIÓN HUISTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1323', 'dep_descripcion' => 'SAN JUAN IXCOY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1324', 'dep_descripcion' => 'SAN ANTONIO HUISTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1325', 'dep_descripcion' => 'SAN SEBASTIÁN COATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1326', 'dep_descripcion' => 'BARILLAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1327', 'dep_descripcion' => 'AGUACATÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1328', 'dep_descripcion' => 'SAN RAFAEL PÉTZAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1329', 'dep_descripcion' => 'SAN GASPAR IXCHIL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1330', 'dep_descripcion' => 'SANTIAGO CHIMALTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1331', 'dep_descripcion' => 'SANTA ANA HUISTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1332', 'dep_descripcion' => 'UNIÓN CANTINIL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1400', 'dep_descripcion' => 'QUICHÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1401', 'dep_descripcion' => 'SANTA CRUZ DEL QUICHÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1402', 'dep_descripcion' => 'CHICHÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1403', 'dep_descripcion' => 'CHINIQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1404', 'dep_descripcion' => 'ZACUALPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1405', 'dep_descripcion' => 'CHAJUL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1406', 'dep_descripcion' => 'CHICHICASTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1407', 'dep_descripcion' => 'PATZITÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1408', 'dep_descripcion' => 'SAN ANTONIO ILOTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1409', 'dep_descripcion' => 'SAN PEDRO JOCOPILAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1410', 'dep_descripcion' => 'CUNÉN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1411', 'dep_descripcion' => 'SAN JUAN COTZAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1412', 'dep_descripcion' => 'JOYABAJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1413', 'dep_descripcion' => 'NEBAJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1414', 'dep_descripcion' => 'SAN ANDRÉS SAJCABAJÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1415', 'dep_descripcion' => 'USPANTÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1416', 'dep_descripcion' => 'SACAPULAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1417', 'dep_descripcion' => 'SAN BARTOLOMÉ JOCOTENANGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1418', 'dep_descripcion' => 'CANILLÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1419', 'dep_descripcion' => 'CHICAMÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1420', 'dep_descripcion' => 'PLAYA GRANDE -IXCÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1421', 'dep_descripcion' => 'PACHALUM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1500', 'dep_descripcion' => 'BAJA VERAPAZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1501', 'dep_descripcion' => 'SALAMÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1502', 'dep_descripcion' => 'SAN MIGUEL CHICAJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1503', 'dep_descripcion' => 'RABINAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1504', 'dep_descripcion' => 'CUBULCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1505', 'dep_descripcion' => 'GRANADOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1506', 'dep_descripcion' => 'EL CHOL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1507', 'dep_descripcion' => 'SAN JERÓNIMO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1508', 'dep_descripcion' => 'PURULHÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1600', 'dep_descripcion' => 'ALTA VERAPAZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1601', 'dep_descripcion' => 'COBÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1602', 'dep_descripcion' => 'SANTA CRUZ VERAPAZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1603', 'dep_descripcion' => 'SAN CRISTÓBAL VERAPAZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1604', 'dep_descripcion' => 'TACTIC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1605', 'dep_descripcion' => 'TAMAHÚ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1606', 'dep_descripcion' => 'TUCURÚ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1607', 'dep_descripcion' => 'PANZÓS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1608', 'dep_descripcion' => 'SENAHÚ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1609', 'dep_descripcion' => 'SAN PEDRO CARCHÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1610', 'dep_descripcion' => 'SAN JUAN CHAMELCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1611', 'dep_descripcion' => 'LANQUÍN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1612', 'dep_descripcion' => 'CAHABÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1613', 'dep_descripcion' => 'CHISEC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1614', 'dep_descripcion' => 'CHAHAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1615', 'dep_descripcion' => 'FRAY BARTOLOMÉ DE LAS CASAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'II1616', 'dep_descripcion' => 'SANTA CATARINA LA TINTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1700', 'dep_descripcion' => 'PETÉN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1701', 'dep_descripcion' => 'FLORES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1702', 'dep_descripcion' => 'SAN JOSÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1703', 'dep_descripcion' => 'SAN BENITO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1704', 'dep_descripcion' => 'SAN ANDRÉS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1705', 'dep_descripcion' => 'LA LIBERTAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1706', 'dep_descripcion' => 'SAN FRANCISCO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1707', 'dep_descripcion' => 'SANTA ANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1708', 'dep_descripcion' => 'DOLORES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1709', 'dep_descripcion' => 'SAN LUIS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1710', 'dep_descripcion' => 'SAYAXCHÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1711', 'dep_descripcion' => 'MELCHOR DE MENCOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'VII1712', 'dep_descripcion' => 'POPTÚN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1800', 'dep_descripcion' => 'IZABAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1801', 'dep_descripcion' => 'PUERTO BARRIOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1802', 'dep_descripcion' => 'LIVINGSTON', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1803', 'dep_descripcion' => 'EL ESTOR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1804', 'dep_descripcion' => 'MORALES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1805', 'dep_descripcion' => 'LOS AMATES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1900', 'dep_descripcion' => 'ZACAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1901', 'dep_descripcion' => 'ZACAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1902', 'dep_descripcion' => 'ESTANZUELA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1903', 'dep_descripcion' => 'RÍO HONDO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1904', 'dep_descripcion' => 'GUALÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1905', 'dep_descripcion' => 'TECULUTÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1906', 'dep_descripcion' => 'USUMATLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1907', 'dep_descripcion' => 'CABAÑAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1908', 'dep_descripcion' => 'SAN DIEGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1909', 'dep_descripcion' => 'LA UNIÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III1910', 'dep_descripcion' => 'HUITÉ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2000', 'dep_descripcion' => 'CHIQUIMULA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2001', 'dep_descripcion' => 'CHIQUIMULA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2002', 'dep_descripcion' => 'SAN JOSÉ LA ARADA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2003', 'dep_descripcion' => 'SAN JUAN ERMITA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2004', 'dep_descripcion' => 'JOCOTÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2005', 'dep_descripcion' => 'CAMOTÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2006', 'dep_descripcion' => 'OLOPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2007', 'dep_descripcion' => 'ESQUIPULAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2008', 'dep_descripcion' => 'CONCEPCIÓN LAS MINAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2009', 'dep_descripcion' => 'QUETZALTEPEQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2010', 'dep_descripcion' => 'SAN JACINTO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'III2011', 'dep_descripcion' => 'IPALA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2100', 'dep_descripcion' => 'JALAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2101', 'dep_descripcion' => 'JALAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2102', 'dep_descripcion' => 'SAN PEDRO PINULA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2103', 'dep_descripcion' => 'SAN LUIS JILOTEPEQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2104', 'dep_descripcion' => 'SAN MANUEL CHAPARRÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2105', 'dep_descripcion' => 'SAN CARLOS ALZATATE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2106', 'dep_descripcion' => 'MONJAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2107', 'dep_descripcion' => 'MATAQUESCUINTLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2200', 'dep_descripcion' => 'JUTIAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2201', 'dep_descripcion' => 'JUTIAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2202', 'dep_descripcion' => 'EL PROGRESO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2203', 'dep_descripcion' => 'SANTA CATARINA MITA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2204', 'dep_descripcion' => 'AGUA BLANCA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2205', 'dep_descripcion' => 'ASUNCIÓN MITA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2206', 'dep_descripcion' => 'YUPILTEPEQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2207', 'dep_descripcion' => 'ATESCATEMPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2208', 'dep_descripcion' => 'JEREZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2209', 'dep_descripcion' => 'EL ADELANTO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2210', 'dep_descripcion' => 'ZAPOTITLÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2211', 'dep_descripcion' => 'COMAPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2212', 'dep_descripcion' => 'JALPATAGUA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2213', 'dep_descripcion' => 'CONGUACO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2214', 'dep_descripcion' => 'MOYUTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2215', 'dep_descripcion' => 'PASACO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2216', 'dep_descripcion' => 'SAN JOSÉ ACATEMPA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['dep_id' => 'IV2217', 'dep_descripcion' => 'QUESADA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],

        ]);
    }
}
