<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\support\Facades\DB;

class EmpresaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('empresa')->insert([
            ['emp_id' => 0, 'emp_nombre' => 'NO APLICA', 'emp_siglas' => '', 'emp_nit' => 'CF', 'emp_municipio' => 'I0101', 'emp_actividad' => '0000', 'emp_descripcion' => 'NO APLICA', 'emp_regimen' => 1, 'emp_fel' => 1, 'emp_inicio' => Carbon::now()->format('Y-m-d'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '0','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'N/A','emp_direccion'=>null, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 1, 'emp_nombre' => 'MEGA SERVICES AND LOGISTIC, SOCIEDAD ANONIMA', 'emp_siglas' => 'MEGA', 'emp_nit' => '55373267', 'emp_municipio' => 'I0101', 'emp_actividad' => '8110.4', 'emp_descripcion' => 'ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES', 'emp_regimen' => 2, 'emp_fel' => 3, 'emp_inicio' =>Carbon::parse('2007-09-12')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '15147822','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'MSL','emp_direccion'=>'12 CALLE 1-25 ZONA 10 CONDOMINIO GEMINIS 10, TORRE NORTE, NIVEL 11','created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 2, 'emp_nombre' => 'ADMINISTRADORA DE SERVICIOS DE TERMINALES Y TALLERES, SOCIEDAD ANONIMA', 'emp_siglas' => 'ATSA', 'emp_nit' => '72715790', 'emp_municipio' => 'I0101', 'emp_actividad' => '5224.4', 'emp_descripcion' => 'MANIPULACIÓN DE LA CARGA', 'emp_regimen' => 2, 'emp_fel' => 3, 'emp_inicio' => Carbon::parse('2010-11-19')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '1542487','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'ATSA','emp_direccion'=>'12 CALLE 1-25 ZONA 10 CONDOMINIO GEMINIS 10, TORRE NORTE, OFICINA 1310', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 3, 'emp_nombre' => 'ADMINISTRADORA DE SERVICIOS MARITIMOS Y TERRESTRES, SOCIEDAD ANONIMA', 'emp_siglas' => 'SERTESA', 'emp_nit' => '39133400', 'emp_municipio' => 'I0101', 'emp_actividad' => '8110.4', 'emp_descripcion' => 'ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES', 'emp_regimen' => 2, 'emp_fel' => 3, 'emp_inicio' => Carbon::parse('2004-12-02')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '25257788','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'SERTESA','emp_direccion'=>'12 CALLE 1-25 ZONA 10, EDIFICIO GEMINIS 10, TORRE NORTE, NIVEL 11, OFICINA 112', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 4, 'emp_nombre' => 'DESARROLLOS PORTUARIOS, SOCIEDAD ANONIMA', 'emp_siglas' => 'DEPSA', 'emp_nit' => '34521771', 'emp_municipio' => 'I0101', 'emp_actividad' => '8110.4', 'emp_descripcion' => 'ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES', 'emp_regimen' => 1, 'emp_fel' => 2, 'emp_inicio' => Carbon::parse('2003-07-25')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '251436','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'DEPSA SANTO TOMAS','emp_direccion'=>'CIUDAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 5, 'emp_nombre' => 'EMPRESA, OPERACIONES Y NEGOCIOS INTERNACIONALES, SOCIEDAD ANONIMA', 'emp_siglas' => 'OPEN', 'emp_nit' => '12515965', 'emp_municipio' => 'I0101', 'emp_actividad' => '0', 'emp_descripcion' => 'No Posee Actividad Economica', 'emp_regimen' => 1, 'emp_fel' => 2, 'emp_inicio' => Carbon::parse('1998-02-18')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '251346','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'OPEN INTER','emp_direccion'=>'CIUDAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 6, 'emp_nombre' => 'NEGOCIOS PORTUARIOS, SOCIEDAD ANONIMA', 'emp_siglas' => 'NEPORSA', 'emp_nit' => '8132887', 'emp_municipio' => 'I0101', 'emp_actividad' => '8110.4', 'emp_descripcion' => 'Actividades Combinadas de Apoyo a Instalaciones', 'emp_regimen' => 1, 'emp_fel' => 2, 'emp_inicio' => Carbon::parse('1996-07-25')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '12548','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'NEPORSA','emp_direccion'=>'CIUDAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 7, 'emp_nombre' => 'ASESORIA Y DESARROLLO DE PROYECTOS INTERNACIONALES, SOCIEDAD ANONIMA', 'emp_siglas' => 'ADPI', 'emp_nit' => '72727942', 'emp_municipio' => 'I0101', 'emp_actividad' => '8110.4', 'emp_descripcion' => 'ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES', 'emp_regimen' => 1, 'emp_fel' => 1, 'emp_inicio' => Carbon::parse('2010-11-19')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83,'emp_numeroIGSS' => '58752','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'ADPI','emp_direccion'=>'CIUDAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 8, 'emp_nombre' => 'DATA EXPERT, SOCIEDAD ANONIMA', 'emp_siglas' => 'DATA', 'emp_nit' => '74416928', 'emp_municipio' => 'I0101', 'emp_actividad' => '6209.4', 'emp_descripcion' => 'Otras Actividades de Tecnologia de la Informacion y de Servicios Informaticos', 'emp_regimen' => 1, 'emp_fel' => 2, 'emp_inicio' => Carbon::parse('2011-01-17')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83,'emp_numeroIGSS' => '0','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'DATA EXPERT','emp_direccion'=>'CIUDAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 9, 'emp_nombre' => 'AGROINDUSTRIAS DE ANIMALES, SOCIEDAD ANONIMA', 'emp_siglas' => 'AGRO', 'emp_nit' => '109268598', 'emp_municipio' => 'I0101', 'emp_actividad' => '10102.4', 'emp_descripcion' => 'Elaboración y Conservación de Carne de Ganado Porcino', 'emp_regimen' => 1, 'emp_fel' => 2, 'emp_inicio' => Carbon::parse('2021-02-02')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83,'emp_numeroIGSS' => '0','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'AGROINDUSTRIAS DE ANIMALES','emp_direccion'=>'CIUDAD','created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 10, 'emp_nombre' => 'PROVEEDORA DE DERIVADOS DEL PETROLEO, SOCIEDAD ANONIMA', 'emp_siglas' => 'PROPETROLEO', 'emp_nit' => '72715340', 'emp_municipio' => 'I0101', 'emp_actividad' => '4610.40', 'emp_descripcion' => 'Venta al por Mayor a Cambio de una Retribución o por Contrata', 'emp_regimen' => 1, 'emp_fel' => 2, 'emp_inicio' => Carbon::parse('2010-11-19')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83,'emp_numeroIGSS' => '0','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'PRO-PETROLEO','emp_direccion'=>'CIUDAD','created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['emp_id' => 11, 'emp_nombre' => 'COMPAÑIA DE SERVICIOS LOGISTICOS MARITIMOS Y TERRESTRES, SOCIEDAD ANONIMA', 'emp_siglas' => 'MARTESA', 'emp_nit' => '110967569', 'emp_municipio' => 'I0101', 'emp_actividad' => '8110.4', 'emp_descripcion' => 'ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES', 'emp_regimen' => 2, 'emp_fel' => 3, 'emp_inicio' => Carbon::parse('2004-12-02')->format('Y-m-d H:i:s'), 'emp_activa' => 1, 'emp_nacionalidad' => 83, 'emp_numeroIGSS' => '25257788','emp_colonia'=>'Edificio Geminis 10','emp_zona'=>'10','emp_calle'=>'12','emp_avenida'=>'1','emp_nomComercial'=>'SERTESA','emp_direccion'=>'12 CALLE 1-25 ZONA 10, EDIFICIO GEMINIS 10, TORRE NORTE, NIVEL 11, OFICINA 112', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ]);
       
    }
}
