<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;


class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('paises')->insert([
            ['pai_id' => 1, 'pai_descripcion' => 'ABUDABI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 2, 'pai_descripcion' => 'AFGANISTAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 143, 'pai_descripcion' => 'ALASKA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 3, 'pai_descripcion' => 'ALBANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 4, 'pai_descripcion' => 'ALEMANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 5, 'pai_descripcion' => 'ALGERIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 198, 'pai_descripcion' => 'ALMIRANTES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 199, 'pai_descripcion' => 'ALTO VOLTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 6, 'pai_descripcion' => 'ANDORRA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 196, 'pai_descripcion' => 'ANGLONORMADAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 7, 'pai_descripcion' => 'ANGOLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 8, 'pai_descripcion' => 'ANGUILLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 9, 'pai_descripcion' => 'ANTARCTICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 10, 'pai_descripcion' => 'ANTIGUA Y BARBUDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 195, 'pai_descripcion' => 'ANTILLAS HOLANDESAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 11, 'pai_descripcion' => 'ARABIA SAUDITA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 200, 'pai_descripcion' => 'ARGELIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 12, 'pai_descripcion' => 'ARGENTINA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 13, 'pai_descripcion' => 'ARMENIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 14, 'pai_descripcion' => 'ARUBA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 15, 'pai_descripcion' => 'AUSTRALIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 16, 'pai_descripcion' => 'AUSTRIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 17, 'pai_descripcion' => 'AZERBAIJAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 197, 'pai_descripcion' => 'AZORES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 18, 'pai_descripcion' => 'BAHAMAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 19, 'pai_descripcion' => 'BAHREIN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 20, 'pai_descripcion' => 'BANGLADESH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 21, 'pai_descripcion' => 'BARBADOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 204, 'pai_descripcion' => 'BARBUDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 22, 'pai_descripcion' => 'BELARUS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 203, 'pai_descripcion' => 'BELAU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 23, 'pai_descripcion' => 'BÉLGICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 24, 'pai_descripcion' => 'BELICE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 25, 'pai_descripcion' => 'BENIN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 26, 'pai_descripcion' => 'BERMUDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 27, 'pai_descripcion' => 'BHUTÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 202, 'pai_descripcion' => 'BIRMANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 28, 'pai_descripcion' => 'BOLIVIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 201, 'pai_descripcion' => 'BORNEO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 29, 'pai_descripcion' => 'BOSNIA Y HERZEGOVINA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 30, 'pai_descripcion' => 'BOTSWANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 31, 'pai_descripcion' => 'BRASIL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 32, 'pai_descripcion' => 'BRUNEI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 33, 'pai_descripcion' => 'BULGARIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 34, 'pai_descripcion' => 'BURKINA FASO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 35, 'pai_descripcion' => 'BURINDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 206, 'pai_descripcion' => 'CAIMAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 207, 'pai_descripcion' => 'CALPE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 36, 'pai_descripcion' => 'CAMEBOYA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 37, 'pai_descripcion' => 'CAMERÚN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 38, 'pai_descripcion' => 'CANADA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 213, 'pai_descripcion' => 'CANARIAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 39, 'pai_descripcion' => 'CAPO VERDE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 215, 'pai_descripcion' => 'CEBELES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 209, 'pai_descripcion' => 'CEILAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 214, 'pai_descripcion' => 'CEUTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 41, 'pai_descripcion' => 'CHAD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 208, 'pai_descripcion' => 'CHECOSLOVAQUIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 42, 'pai_descripcion' => 'CHILE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 43, 'pai_descripcion' => 'CHINA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 52, 'pai_descripcion' => 'CHIPRE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 211, 'pai_descripcion' => 'CLIPPERTON', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 210, 'pai_descripcion' => 'COCOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 44, 'pai_descripcion' => 'COLOMBIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 45, 'pai_descripcion' => 'COMORO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 46, 'pai_descripcion' => 'CONGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 212, 'pai_descripcion' => 'COOK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 48, 'pai_descripcion' => 'COREA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 47, 'pai_descripcion' => 'COREA DEL SUR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 50, 'pai_descripcion' => 'COSTA DE MARFIL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 49, 'pai_descripcion' => 'COSTA RICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 53, 'pai_descripcion' => 'CROACIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 54, 'pai_descripcion' => 'DINAMARCA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 55, 'pai_descripcion' => 'DJIBOUTI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 56, 'pai_descripcion' => 'DOMINICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 58, 'pai_descripcion' => 'DUBAI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 59, 'pai_descripcion' => 'ECUADOR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 60, 'pai_descripcion' => 'EGIPTO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 61, 'pai_descripcion' => 'EL SALVADOR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 62, 'pai_descripcion' => 'EMIRATOS ÁRABES UNIDOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 63, 'pai_descripcion' => 'ERITREA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 216, 'pai_descripcion' => 'ESCOCIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 64, 'pai_descripcion' => 'ESLOVAQUIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 65, 'pai_descripcion' => 'ESLOVENIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 109, 'pai_descripcion' => 'ESOTHO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 66, 'pai_descripcion' => 'ESPAÑA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 67, 'pai_descripcion' => 'ESTADOS UNIDOS DE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 68, 'pai_descripcion' => 'ESTONIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 69, 'pai_descripcion' => 'ETIOPIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 217, 'pai_descripcion' => 'FEDERACION DE MALASIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 219, 'pai_descripcion' => 'FEREO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 70, 'pai_descripcion' => 'FIJI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 71, 'pai_descripcion' => 'FILIPINAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 72, 'pai_descripcion' => 'FINLANDIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 218, 'pai_descripcion' => 'FORMOSA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 73, 'pai_descripcion' => 'FRANCIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 74, 'pai_descripcion' => 'GABÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 75, 'pai_descripcion' => 'GAMBIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 76, 'pai_descripcion' => 'GEORGIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 77, 'pai_descripcion' => 'GHANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 78, 'pai_descripcion' => 'GIBRALTAR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 223, 'pai_descripcion' => 'GILBERT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 220, 'pai_descripcion' => 'GRAN BRETAÑA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 79, 'pai_descripcion' => 'GRECIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 81, 'pai_descripcion' => 'GRANADA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 80, 'pai_descripcion' => 'GROENLANDIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 82, 'pai_descripcion' => 'GUADALUPE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 222, 'pai_descripcion' => 'GUAM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 83, 'pai_descripcion' => 'GUATEMALA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 221, 'pai_descripcion' => 'GUAYANA INGLESA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 84, 'pai_descripcion' => 'GUINEA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 85, 'pai_descripcion' => 'GUINEA ECUATORIAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 224, 'pai_descripcion' => 'GUINEA PORTUGUESA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 86, 'pai_descripcion' => 'GUYANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 87, 'pai_descripcion' => 'HAITI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 225, 'pai_descripcion' => 'HAWAI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 88, 'pai_descripcion' => 'HOLANDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 89, 'pai_descripcion' => 'HONDURAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 90, 'pai_descripcion' => 'HONG KONG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 91, 'pai_descripcion' => 'HUNGRIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 93, 'pai_descripcion' => 'INDIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 94, 'pai_descripcion' => 'INDONESIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 226, 'pai_descripcion' => 'INGLATERRA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 95, 'pai_descripcion' => 'IRAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 96, 'pai_descripcion' => 'IRAQ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 227, 'pai_descripcion' => 'IRIAN JAYA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 97, 'pai_descripcion' => 'IRLANDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 228, 'pai_descripcion' => 'ISLA HONG KONG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 92, 'pai_descripcion' => 'ISLANDIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 98, 'pai_descripcion' => 'ISRAEL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 99, 'pai_descripcion' => 'ITALIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 100, 'pai_descripcion' => 'JAMAICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 101, 'pai_descripcion' => 'JAPÓN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 102, 'pai_descripcion' => 'JORDANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 230, 'pai_descripcion' => 'KATAR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 103, 'pai_descripcion' => 'KAZAKHSTAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 104, 'pai_descripcion' => 'KENIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 229, 'pai_descripcion' => 'KOWEIT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 105, 'pai_descripcion' => 'KUWAIT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 106, 'pai_descripcion' => 'KYRGYZSTAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 107, 'pai_descripcion' => 'LATVIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 231, 'pai_descripcion' => 'LESHOTO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 110, 'pai_descripcion' => 'LETONIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 108, 'pai_descripcion' => 'LIBANO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 111, 'pai_descripcion' => 'LIBERIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 112, 'pai_descripcion' => 'LIBIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 113, 'pai_descripcion' => 'LIECHTENSTEIN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 114, 'pai_descripcion' => 'LITUANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 115, 'pai_descripcion' => 'LUXEMBURGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 116, 'pai_descripcion' => 'MACEDONIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 235, 'pai_descripcion' => 'MACQUANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 117, 'pai_descripcion' => 'MADAGASCAR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 236, 'pai_descripcion' => 'MADEITA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 119, 'pai_descripcion' => 'MALASIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 118, 'pai_descripcion' => 'MALAWI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 232, 'pai_descripcion' => 'MALASIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 120, 'pai_descripcion' => 'MALDIVES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 121, 'pai_descripcion' => 'MALI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 122, 'pai_descripcion' => 'MALTA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 238, 'pai_descripcion' => 'MAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 133, 'pai_descripcion' => 'MARRUECOS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 123, 'pai_descripcion' => 'MARTINICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 124, 'pai_descripcion' => 'MAURITANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 125, 'pai_descripcion' => 'MAURITIUS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 126, 'pai_descripcion' => 'MAYOTTE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 233, 'pai_descripcion' => 'MELILLA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 127, 'pai_descripcion' => 'MEXICO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 128, 'pai_descripcion' => 'MICRONESIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 237, 'pai_descripcion' => 'MIDWAY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 129, 'pai_descripcion' => 'MOLDOVA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 234, 'pai_descripcion' => 'MOLUCA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 130, 'pai_descripcion' => 'MONACO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 131, 'pai_descripcion' => 'MONGOLIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 132, 'pai_descripcion' => 'MONTSERRAT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 134, 'pai_descripcion' => 'MOZAMBIQUE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 135, 'pai_descripcion' => 'NAMIBIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 136, 'pai_descripcion' => 'NEOAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 138, 'pai_descripcion' => 'NICARAGUA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 139, 'pai_descripcion' => 'NIGER', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 140, 'pai_descripcion' => 'NIGERIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 239, 'pai_descripcion' => 'NORFOLK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 141, 'pai_descripcion' => 'NORUEGA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 240, 'pai_descripcion' => 'NUEVA CALEDONIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 137, 'pai_descripcion' => 'NUEVA ZELANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 142, 'pai_descripcion' => 'OMÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 243, 'pai_descripcion' => 'PALAU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 145, 'pai_descripcion' => 'PALESTINA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 146, 'pai_descripcion' => 'PANAMÁ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 147, 'pai_descripcion' => 'PAPUA NUEVA GUINEA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 144, 'pai_descripcion' => 'PAQUISTÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 148, 'pai_descripcion' => 'PARAGUAY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 244, 'pai_descripcion' => 'PASCUA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 149, 'pai_descripcion' => 'PERÚ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 245, 'pai_descripcion' => 'PITCAIRN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 246, 'pai_descripcion' => 'POLONESIA FRANCESA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 150, 'pai_descripcion' => 'POLONIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 241, 'pai_descripcion' => 'POPULAR DE CHINA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 242, 'pai_descripcion' => 'POPULAR DE COREA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 151, 'pai_descripcion' => 'PORTUGAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 152, 'pai_descripcion' => 'PUERTO RICO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 153, 'pai_descripcion' => 'QATAR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 154, 'pai_descripcion' => 'REINO UNIDO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 247, 'pai_descripcion' => 'REPUBLICA ARABE DE EJIPTO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 40, 'pai_descripcion' => 'REPÚBLICA CETNROAFRICANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 51, 'pai_descripcion' => 'REPUBLICA CHECA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 248, 'pai_descripcion' => 'REPUBLICA DE AFRICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 57, 'pai_descripcion' => 'REPÚBLICA DOMINICANA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 155, 'pai_descripcion' => 'REUNION', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 156, 'pai_descripcion' => 'RUMANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 157, 'pai_descripcion' => 'RUSIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 158, 'pai_descripcion' => 'RWANDA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 250, 'pai_descripcion' => 'SALOMON DEL SUR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 159, 'pai_descripcion' => 'SAMOA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 160, 'pai_descripcion' => 'SAN MARINO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 251, 'pai_descripcion' => 'SANTA LUCIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 161, 'pai_descripcion' => 'SAO TOME Y PRINCIPE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 162, 'pai_descripcion' => 'SENEGAL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 163, 'pai_descripcion' => 'SEYCHELLES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 164, 'pai_descripcion' => 'SIERRA LEONA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 165, 'pai_descripcion' => 'SINGAPUR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 166, 'pai_descripcion' => 'SIRIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 249, 'pai_descripcion' => 'SOCOTORRA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 167, 'pai_descripcion' => 'SOMALIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 169, 'pai_descripcion' => 'SRILANKA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 170, 'pai_descripcion' => 'SUDÁN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 173, 'pai_descripcion' => 'SUECIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 174, 'pai_descripcion' => 'SUIZA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 168, 'pai_descripcion' => 'SUDAFRICA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 171, 'pai_descripcion' => 'SURINAME', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 172, 'pai_descripcion' => 'SWAZILANDIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 178, 'pai_descripcion' => 'TAILANDIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 175, 'pai_descripcion' => 'TAIWAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 176, 'pai_descripcion' => 'TAJIKISTAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 177, 'pai_descripcion' => 'TANZANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 252, 'pai_descripcion' => 'TIMOR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 179, 'pai_descripcion' => 'TOGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 253, 'pai_descripcion' => 'TOKELAU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 180, 'pai_descripcion' => 'TONGA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 181, 'pai_descripcion' => 'TRINIDAD Y TOBAGO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 182, 'pai_descripcion' => 'TÚNES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 184, 'pai_descripcion' => 'TURKMENISTAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 183, 'pai_descripcion' => 'TURQUIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 254, 'pai_descripcion' => 'TUVALU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 185, 'pai_descripcion' => 'UCRANIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 186, 'pai_descripcion' => 'UGANGA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 187, 'pai_descripcion' => 'URUGUAY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 188, 'pai_descripcion' => 'UZBEKISTAN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 257, 'pai_descripcion' => 'VATICANO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 189, 'pai_descripcion' => 'VENEZUELA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 190, 'pai_descripcion' => 'VIETNAM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 256, 'pai_descripcion' => 'VIRGENES AMERICANAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 255, 'pai_descripcion' => 'VIRGENES BRITANICAS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 258, 'pai_descripcion' => 'WAKE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 259, 'pai_descripcion' => 'WALLIS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 191, 'pai_descripcion' => 'YEMEN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 192, 'pai_descripcion' => 'YUGOSLAVIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 193, 'pai_descripcion' => 'ZAMBIA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['pai_id' => 194, 'pai_descripcion' => 'ZIMBABWE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ]);
    }
}
